apiVersion: v2
name: persistent-petitioner
description: Persistent Petitioner â€” automate signing political petitions from email. IMAP + Playwright.
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.22.0-0"
keywords:
  - petition
  - automation
  - email
  - playwright
maintainers: []
dependencies:
  - name: onepassworditem
    version: "1.1.0"
    repository: https://expectedbehaviors.github.io/OnePasswordItem-helm
